# Generated by Django 4.2 on 2023-05-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomePaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="income",
            name="income_payment_method",
            field=models.ForeignKey(
                choices=[("cash", "cash"), ("card", "card")],
                on_delete=django.db.models.deletion.CASCADE,
                to="main_page.incomepaymentmethod",
            ),
        ),
    ]
