# Generated by Django 4.1.6 on 2023-05-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomePaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=100)),
                (
                    "income_payment_method",
                    models.ForeignKey(
                        choices=[("cash", "cash"), ("card", "card")],
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.incomepaymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        choices=[
                            ("canada", "canada"),
                            ("usa", "usa"),
                            ("europe", "europe"),
                        ],
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.location",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        choices=[
                            ("cash", "cash"),
                            ("credit", "credit card"),
                            ("debit", "debit card"),
                            ("bank_transfer", "bank transfer"),
                        ],
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.paymentmethod",
                    ),
                ),
            ],
        ),
    ]
