# Generated by Django 4.2 on 2023-05-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0002_incomepaymentmethod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="location",
            field=models.ForeignKey(
                choices=[
                    ("vancouver", "vancouver"),
                    ("toronto", "toronto"),
                    ("burnaby", "burnaby"),
                    ("richmond", "richmond"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to="main_page.location",
            ),
        ),
    ]
