# Generated by Django 4.1.6 on 2023-05-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0003_remove_expense_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(auto_now_add=True, max_length=50),
        ),
    ]
