# Generated by Django 4.1.6 on 2023-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0004_alter_expense_date_alter_expense_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense", name="date", field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name="income", name="date", field=models.DateField(max_length=50),
        ),
    ]
