# Generated by Django 4.2 on 2023-05-16 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0004_alter_expense_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.ForeignKey(
                choices=[
                    ("cash", "cash"),
                    ("credit", "credit card"),
                    ("debit", "debit card"),
                    ("bank_transfer", "bank transfer"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to="main_page.paymentmethod",
            ),
        ),
    ]
