# Generated by Django 4.1.6 on 2023-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0007_alter_category_user_alter_expense_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="custom_category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="income",
            name="custom_category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fod", "Food"),
                    ("Clothes", "Clothes"),
                    ("Rent", "Rent"),
                    ("Another_expenses", "Another Expenses"),
                ],
                default="1",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.CharField(
                choices=[
                    ("Work1", "Work 1"),
                    ("Work2", "Work 2"),
                    ("Work3", "Work 3"),
                    ("Foreign_income", "Foreign Income"),
                    ("Investments", "Investments"),
                ],
                default="1",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
